package no.nav.bidrag.beregn.forskudd.core.enums

enum class ResultatKode {
  AVSLAG,
  REDUSERT_FORSKUDD_50_PROSENT,
  ORDINAERT_FORSKUDD_75_PROSENT,
  FORHOYET_FORSKUDD_100_PROSENT,
  FORHOYET_FORSKUDD_11_AAR_125_PROSENT,
  FORSKUDD_ENSLIG_ASYLANT_200_PROSENT,
  FORSKUDD_ENSLIG_ASYLANT_11_AAR_250_PROSENT
}