name: maven deploy
on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls -all && cat README.md
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: '13'
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: echo ::set-output name=tag::${ mvn help:evaluate -Dexpression=bidrag-beregn-felles.version  -q -DforceStdout }
        id: dependency
      - run: echo "checkout tagged version ${{ steps.depencdency.outputs.tag }}"
      - name: Checkout tagged version of bidrag-beregn-felles
        uses: actions/checkout@v2
        with:
          repository: navikt/bidrag-beregn-felles
          ref: ${{ steps.depencdency.outputs.tag }}
      - run: pwd && ls -all && cat README.md
      - run: cd bidrag-beregn-felles
      - run: mvn -B install -e -DskipTests
      - uses: actions/checkout@v2
      - uses: navikt/bidrag-maven/verify-dependencies@v1
      - run: mvn -B install -e
      - uses: navikt/bidrag-release/prepare-mvn-pkg@v3
        id: prepare
        if: github.ref == 'refs/heads/master'
      - uses: navikt/bidrag-release/verify-auto-release@v3
        id: verify
        if: github.ref == 'refs/heads/master'
        with:
          changelog_file: README.md
          release_version: ${{ steps.prepare.outputs.release_version }}
      - uses: navikt/bidrag-release/mvn-github-pkg@v3
        if: github.ref == 'refs/heads/master'
        with:
          is_release_candidate: ${{ steps.verify.outputs.is_release_candidate }}
          new_snapshot_version: ${{ steps.prepare.outputs.new_snapshot_version }}
          release_version: ${{ steps.prepare.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-release/tag-n-commit-release@v3
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Bumped to new SNAPSHOT version after release of version ${{ steps.prepare.outputs.release_version }}
          tag_message: Released new version - ${{ steps.prepare.outputs.release_version }}
          pattern: pom.xml
          is_release_candidate: ${{ steps.verify.outputs.is_release_candidate }}
          tag: ${{ steps.prepare.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
